/// Flutter icons Timetable
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Timetable
///      fonts:
///       - asset: fonts/Timetable.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Timetable {
  Timetable._();

  static const _kFontFam = 'Timetable';

  static const IconData computerArchitecture = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData hostel = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData informationTheory = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData speechCulture = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData physics = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData chemistry = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData literature = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData math = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData informatics = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData geography = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData history = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData lifeSafety = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData biology = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData socialStudies = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData physicalCulture = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData ethics = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData management = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData softwareDevelopment = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData computerGraphic = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData databases = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData english = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData economics = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData philosophy = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData academy = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData project_development = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData operatingSystems = const IconData(0xe81d, fontFamily: _kFontFam);
}
